const express = require('express');
const puppeteer = require('puppeteer');
const nodemailer = require('nodemailer');
const cors = require('cors');
const path = require('path');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use(express.static('public'));

// Configuração do Nodemailerconst transporter = nodemailer.createTransport({
  service: 'outlook',
    auth: {
        user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASSWORD
              }
              });

              // Estado global para armazenar status da operação
              let operationStatus = {};

              // Rota para enviar fichaapp.post('/api/enviar-ficha', async (req, res) => {
                try {
                    const { clientData } = req.body;
                        const operationId = Date.now().toString();

                                operationStatus[operationId] = {
                                      id: operationId,
                                            status: 'processando',
                                                  timestamp: new Date(),
                                                        cpf: clientData.cpf,
                                                              nome: clientData.nome
                                                                  };

                                                                      // Enviar para Fandi em background    procesarFandi(clientData, operationId).catch(err => {
                                                                            operationStatus[operationId].status = 'erro';
                                                                                  operationStatus[operationId].erro = err.message;
                                                                                      });

                                                                                          res.json({ 
                                                                                                success: true, 
                                                                                                      operationId,
                                                                                                            message: 'Ficha enviada para processamento'
                                                                                                                });
                                                                                                                  } catch (error) {
                                                                                                                      res.status(500).json({ success: false, error: error.message });
                                                                                                                        }
                                                                                                                        });
                                                                                                                        
                                                                                                                        // Rota para verificar statusapp.get('/api/status/:operationId', (req, res) => {
                                                                                                                          const { operationId } = req.params;
                                                                                                                            const status = operationStatus[operationId];
                                                                                                                              
                                                                                                                                if (!status) {
                                                                                                                                    return res.status(404).json({ error: 'Operação não encontrada' });
                                                                                                                                      }
                                                                                                                                        
                                                                                                                                          res.json(status);
                                                                                                                                          });
                                                                                                                                          
                                                                                                                                          // Rota para enviar emailapp.post('/api/enviar-email', async (req, res) => {
                                                                                                                                            try {
                                                                                                                                                const { cpf, nome, operationId } = req.body;
                                                                                                                                                    
                                                                                                                                                        const mailOptions = {
                                                                                                                                                              from: process.env.EMAIL_USER,
                                                                                                                                                                    to: [
                                                                                                                                                                            'marcelo.sinhorine@tdrive.com.br',
                                                                                                                                                                                    'douglas.pinto@tdrive.com.br',
                                                                                                                                                                                            'eliane.psilva@tdrive.com.br',
                                                                                                                                                                                                    'feitoyota@automob.com.br'
                                                                                                                                                                                                          ].join(','),
                                                                                                                                                                                                                subject: 'Sequenciar ficha',
                                                                                                                                                                                                                      html: `<p><strong>CPF:</strong> ${cpf}</p><p><strong>Nome:</strong> ${nome}</p>`
                                                                                                                                                                                                                          };
                                                                                                                                                                                                                          
                                                                                                                                                                                                                              await transporter.sendMail(mailOptions);
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                      operationStatus[operationId].emailEnviado = true;
                                                                                                                                                                                                                                          operationStatus[operationId].statusEmail = 'enviado';
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                              res.json({ success: true, message: 'Email enviado com sucesso' });
                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                    res.status(500).json({ success: false, error: error.message });
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                      // Função para processar Fandiasync function procesarFandi(clientData, operationId) {
                                                                                                                                                                                                                                                        let browser;
                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                              browser = await puppeteer.launch({ headless: false });
                                                                                                                                                                                                                                                                  const page = await browser.newPage();
                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                          await page.goto('https://jsl.fandi.com.br/operacao/nova', {
                                                                                                                                                                                                                                                                                waitUntil: 'networkidle2'
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                        // Preencher departamento
                                                                                                                                                                                                                                                                                            await page.select('select[name="departamento"]', clientData.departamento);
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                    // Inserir CPF    await page.type('input[name="cpf"]', clientData.cpf);
                                                                                                                                                                                                                                                                                                        await page.waitForTimeout(500);
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                // Verificar se existe cadastro ou criar novo    const cpfInput = await page.$('input[name="cpf"]');
                                                                                                                                                                                                                                                                                                                    await cpfInput.press('Tab');
                                                                                                                                                                                                                                                                                                                        await page.waitForTimeout(1000);
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                            // Verificar se é cliente novo
                                                                                                                                                                                                                                                                                                                                const clienteNovoIndicador = await page.$('div[class*="cliente-novo"]');
                                                                                                                                                                                                                                                                                                                                    if (clienteNovoIndicador) {
                                                                                                                                                                                                                                                                                                                                          // Preencher dados do cliente novo
                                                                                                                                                                                                                                                                                                                                                await page.type('input[name="nome"]', clientData.nome);
                                                                                                                                                                                                                                                                                                                                                      await page.type('input[name="rg"]', clientData.rg || '0000000');
                                                                                                                                                                                                                                                                                                                                                            await page.type('input[name="dataNascimento"]', clientData.dataNascimento || '01/01/1990');
                                                                                                                                                                                                                                                                                                                                                                  await page.type('input[name="email"]', clientData.email || 'cliente@default.com');
                                                                                                                                                                                                                                                                                                                                                                        await page.type('input[name="celular"]', clientData.celular || '11999999999');
                                                                                                                                                                                                                                                                                                                                                                              await page.type('input[name="cep"]', clientData.cep || '00000000');
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                          // Preench outros campos...      await page.waitForTimeout(500);
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                  // Preencher veículo (ordem importante: ano fab, ano modelo, marca, modelo, versão, valor, km)
                                                                                                                                                                                                                                                                                                                                                                                                      await page.type('input[name="anoFabricacao"]', clientData.anoFabricacao);
                                                                                                                                                                                                                                                                                                                                                                                                          await page.waitForTimeout(300);
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                  await page.type('input[name="anoModelo"]', clientData.anoModelo);
                                                                                                                                                                                                                                                                                                                                                                                                                      await page.waitForTimeout(300);
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                              await page.select('select[name="marca"]', clientData.marca);
                                                                                                                                                                                                                                                                                                                                                                                                                                  await page.waitForTimeout(300);
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                          await page.select('select[name="modelo"]', clientData.modelo);
                                                                                                                                                                                                                                                                                                                                                                                                                                              await page.waitForTimeout(300);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                      await page.select('select[name="versao"]', clientData.versao);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          await page.waitForTimeout(300);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Preencher valor SEM formatação    await page.type('input[name="valor"]', clientData.valor.replace(/\D/g, ''));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await page.waitForTimeout(300);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await page.type('input[name="quilometragem"]', clientData.km);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Preencher condições de venda
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await page.type('input[name="entrada"]', clientData.entrada || '0');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await page.type('input[name="parcelas"]', clientData.parcelas || '1');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Enviar operação    await page.click('button[class*="enviar"]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await page.waitForTimeout(2000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          operationStatus[operationId].status = 'concluido';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              operationStatus[operationId].fidChIP = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        operationStatus[operationId].status = 'erro';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            operationStatus[operationId].erro = error.message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                throw error;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (browser) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await browser.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Servir a página HTMLapp.get('/', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.sendFile(path.join(__dirname, 'public', 'index.html'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`Servidor rodando em http://localhost:${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
